config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :home, only: %w[index]
  resources :booking, only: %w[index create destroy]
  resources :contact_us, only: %w[index create]
  get 'service_list/:id', to: 'home#service_list', as: 'service_list'
  get 'about_us', to: 'home#about_us', as: 'about_us'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  resourcify
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  validates :name, :email, :address, :mobile_number, :service, :service_rate, :date, presence: true
  validates :mobile_number, uniqueness: true, numericality: true, length: { minimum: 10, maximum: 10 }
end

app/models/contact_us.rb
class ContactUs < ApplicationRecord
  validates :name, :mobile_number, :message, presence: true
  validates :mobile_number, uniqueness: true, numericality: true, length: { minimum: 10, maximum: 10 }
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :service_lists

  validates :name, :image, presence: true
end

app/models/service_list.rb
class ServiceList < ApplicationRecord
  
  validates :name, :rate, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable, :registerable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/booking_controller.rb
class BookingController < ApplicationController
  before_action :authenticate_user!

  def index
    # @bookings = Booking.all
    @booking = Booking.find_by_email current_user.email
    @service_names = Service.all.collect(&:name)
    @service_list = []
    ServiceList.all.collect { |s| @service_list.push("#{s.name} --> #{s.rate}") }
  end

  def create
    booking = Booking.new(booking_params)
    booking.email = current_user.email
    if booking.save
      flash[:success] = 'Booking Successfully Created'
    else
      flash[:error] = booking.errors.full_messages
    end
    redirect_to booking_index_path
  end

  def destroy
    Booking.delete(params[:id])
    flash[:destroy] = 'Booking canceled'
    redirect_to booking_index_path
  end

  private

  def booking_params
    params.permit(:name, :address, :mobile_number, :date, :service, :service_rate)
  end
end

app/controllers/contact_us_controller.rb
class ContactUsController < ApplicationController
  def index
  end

  def create
    contact_us = ContactUs.new(contact_us_params)
    if contact_us.save
      flash[:success] = 'Details save successfully!'
    else
      flash[:error] = contact_us.errors.full_messages
    end
    redirect_to contact_us_path
  end

  private

  def contact_us_params
    params.permit(:name, :mobile_number, :message)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @services = Service.where(active: true)
  end

  def service_list
    @service_lists = ServiceList.where(service_id: params[:id])
  end

  def about_us
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/booking/_form.html.haml
= form_for :booking do |f|
  .form-group.booking-form
    - if flash[:success]
      %div.alert.alert-success=flash[:success]
    - elsif flash[:error]
      - flash[:error].each do |error|
        %div.alert.alert-danger=error   
    .row.mb-2
      .col-12.mt-2.mb-2 
        =f.label 'name', :id => 'input-control' 
        %input.form-control(type='text' placeholder='Enter Name' name='name' required)
      .col-12.mt-2.mb-2 
        =f.label 'Address', :id => 'input-control'
        %textarea.form-control(type='text' placeholder='Enter address' name='address' rows='2' required)
      .col-12.mt-2.mb-2 
        =f.label 'Mobile Number', id: 'input-control'
        %input.form-control(type='number' placeholder='Enter mobile number' name='mobile_number' required)
      .col-12.mt-2.mb-2
        =f.label 'Select Service', :id => 'input-control'
        = select_tag 'service', options_for_select(@service_names), :class => 'form-control'
      .col-12.mt-2.mb-2
        =f.label 'Select Rate', :id => 'input-control'
        -# %select.form-control#service(name='service_rate')
        -#   %option(value='300' selected)='300'
        -#   %option(value='500')='500'
        = select_tag 'service_rate', options_for_select(@service_list), :class => 'form-control'
      .col-12.mt-2.mb-2
        =f.label 'select date', :id => 'input-control'
        %input.form-control(type='date' name='date' required) 
      .col-12.mt-2.mb-2.text-center 
        = f.button 'Book', :class=>'btn btn-booking', :name => 'Book'

app/views/booking/index.html.haml
// *********** header
= render :partial => 'partials/header'

// *********** Booking 
%div.home-background
  %div.row.m-0.pt-5
    %div.col-md-6.p-5 
      %h3.text-center='Booking'
      %div.display-booking 
        - if flash[:destroy]
          %div.alert.alert-danger=flash[:destroy]
        - elsif @booking.nil?
          %div.alert.alert-primary='you have not done booking'
        - else
          %div.row
            %div.col-md-6
              %p='Name'
            %div.col-md-6
              %p=@booking.name
          %div.row
            %div.col-md-6
              %p='Address'
            %div.col-md-6
              %p=@booking.address
          %div.row
            %div.col-md-6
              %p='Phone'
            %div.col-md-6
              %p=@booking.mobile_number
          %div.row
            %div.col-md-6
              %p='Service'
            %div.col-md-6
              %p=@booking.service
          %div.row
            %div.col-md-6
              %p='Rate'
            %div.col-md-6
              %p=@booking.service_rate
          %div.row
            %div.col-md-6
              %p='Date'
            %div.col-md-6
              %p=@booking.date
          %div.row
            %div.col-md-6
              = link_to('Edit booking', '', :class => 'btn btn-success')
            %div.col-md-6
              = link_to('cancel booking', booking_path(@booking.id), :method => "DELETE", :class => 'btn btn-danger')    
    %div.col-md-6
      - if @booking.nil?
        = render :partial => 'booking/form'

app/views/contact_us/_form.html.haml
= form_for :contact_us, :method => 'post' do |f|
  .form-group.booking-form
    - if flash[:success]
      %div.alert.alert-success=flash[:success]
    - elsif flash[:error]
      - flash[:error].each do |error|
        %div.alert.alert-danger=error   
    .row.mb-2
      .col-12.mt-2.mb-2 
        =f.label 'name', :id => 'input-control' 
        %input.form-control(type='text' placeholder='Enter Name' name='name' required)
      .col-12.mt-2.mb-2 
        =f.label 'Mobile Number', :id => 'input-control'
        %input.form-control(type='number' placeholder='Enter mobile number' name='mobile_number' required)
      .col-12.mt-2.mb-2 
        =f.label 'Message', :id => 'input-control'
        %textarea.form-control(type='text' placeholder='Enter Message' name='message' rows='2' required)
      .col-12.mt-2.mb-2.text-center 
        = f.button 'submit', :class=>'btn btn-booking'

app/views/contact_us/index.html.haml
// *********** header Section
= render :partial => 'partials/header'

%div.home-background
  %div.row.m-0.pt-5
    %div.col-md-6.offset-md-3
      = render :partial => 'contact_us/form'

// *********** footer Section
= render :partial => 'partials/footer'

app/views/home/about_us.html.haml
// *********** header Section
= render :partial => 'partials/header'

%div.home-background
  %div.row.m-0.pt-5.text-center
    %div.col-md-12
      %h1='About Parlour'

// *********** footer Section
= render :partial => 'partials/footer'

app/views/home/index.html.haml
// *********** header Section
= render :partial => 'partials/header'

// *********** home Section
%div.home-background 
  %div.row
    %div.col-md-12.card-contain
      %h1.mb-4="Some Heading"    
      = link_to('Do Booking', booking_index_url, :class => 'btn btn-booking')

// *********** Our services Section
%div.container
  // ---- services
  %h1.mt-3.mb-3.text-center='Our Services'
  %div.row.mt-5
    - @services.each do |service|
      = link_to service_list_path(service.id), :id => 'service_list', :class => 'col-md-3 col-sm-6' do
        %div.text-center 
          %img.rounded-circle(src='https://picsum.photos/200' alt="")/
          %h4.mt-3=service.name

  // ---- Booking cards
  %div.row.mt-5
    %h1.mt-3.mb-3.text-center='Book your slots'
    %div.col-md-4
      %div.card
        %img(src='https://picsum.photos/200' alt="")/
        %div.card-body
          %h5.card-title='Card title'
          %p.card-text='Some quick example text to build on the card title and make up the bulk of the cards content.'
          = link_to('Booking', booking_index_url, :class => 'nav-link text-center btn btn-outline-primary btn-sm btn-block') 
    %div.col-md-4
      %div.card
        %img(src='https://picsum.photos/200' alt="")/
        %div.card-body
          %h5.card-title='Card title'
          %p.card-text='Some quick example text to build on the card title and make up the bulk of the cards content.'
          = link_to('Booking', booking_index_url, :class => 'nav-link text-center btn btn-outline-primary btn-sm btn-block')
    %div.col-md-4
      %div.card
        %img(src='https://picsum.photos/200' alt="")/
        %div.card-body
          %h5.card-title='Card title'
          %p.card-text='Some quick example text to build on the card title and make up the bulk of the cards content.'
          = link_to('Booking', booking_index_url, :class => 'nav-link text-center btn btn-outline-primary btn-sm btn-block') 

// *********** footer Section
= render :partial => 'partials/footer'

app/views/home/service_list.html.haml
// *********** header Section
= render :partial => 'partials/header'

%div.home-background
  %div.row.m-0.pt-5
    %div.col-md-12.p-5 
      %h3.text-center='List and prices'
      %div.display-booking 
        - if @service_lists.empty?
          %div.alert.alert-primary='List Not present'
        - else
          %div.row
            %div.col-md-6
              %h2='Name'
            %div.col-md-6
              %h2='Rate'
          %hr
          - @service_lists.each do |service_list|
            %div.row
              %div.col-md-6
                %h5=service_list.name
              %div.col-md-6
                %h5="#{service_list.rate} Rs"

// *********** footer Section
= render :partial => 'partials/footer'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParlourProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'home', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'booking', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/partials/_footer.html.haml
%div.footer.mt-5.mb-5
  %h1.text-center='footer part' 

app/views/partials/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container
    %a.navbar-brand(href=root_url)="ChetnaBeauty"
    %button.navbar-toggler='Home'
    %div.collapse.navbar-collapse.d-flex.flex-row-reverse
      %ul.navbar-nav
        %li.nav-item.active
          = link_to('Home', root_url, :class => 'nav-link')
        %li.nav-item
          = link_to('About Us', about_us_path, :class => 'nav-link')
        %li.nav-item
          = link_to('Services', '/#service_list', :class => 'nav-link')
        %li.nav-item
          = link_to('Contact Us', contact_us_path, :class => 'nav-link')
        %li.nav-item
        - if user_signed_in?
          = link_to('Logout', destroy_user_session_url, :method => :delete, :class => 'btn btn-booking')
        - else
          = link_to('Login', new_user_session_url, :class => 'btn btn-booking')